# One image: caddy in front, nuxt and the rust api behind it on loopback.
#
# Base images are pinned to a minor rather than a floating tag. A moving base is
# the largest supply-chain surface in a build, and pinning the dependencies
# inside it while the image itself drifts achieves little.
ARG NODE_VERSION=26.0-alpine
ARG RUST_VERSION=1.98-alpine
ARG CADDY_VERSION=2.10-alpine

# web deps
# Split from the build so a source-only change reuses the install layer.
FROM node:${NODE_VERSION} AS web-deps

WORKDIR /build
COPY web/package.json web/package-lock.json web/.npmrc ./

# --ignore-scripts blocks postinstall hooks, the usual delivery mechanism for a
# compromised package. nuxt prepare runs explicitly in the next stage.
RUN npm ci --ignore-scripts

# web build
FROM node:${NODE_VERSION} AS web-build

WORKDIR /build
COPY --from=web-deps /build/node_modules ./node_modules
COPY web/ .

ENV NODE_ENV=production
ENV NUXT_TELEMETRY_DISABLED=1

RUN npx nuxt prepare && npx nuxt build

# api build
FROM rust:${RUST_VERSION} AS api-build

RUN apk add --no-cache musl-dev

WORKDIR /build

COPY Cargo.toml Cargo.lock ./
COPY crates ./crates

# Cache mounts rather than a stub-manifest layer: the workspace has several
# crates and every one needs a real manifest before cargo will resolve it. The
# mounted target dir does not survive into the layer, hence the copy out.
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/build/target \
    cargo build --release --locked -p lighthouse-api \
    && cp target/release/lighthouse-api /usr/local/bin/lighthouse-api

# runtime
FROM caddy:${CADDY_VERSION} AS runtime

# bash for the entrypoint's `wait -n`, nodejs to run the nitro output. The rust
# binary is static against musl and needs nothing.
RUN apk add --no-cache bash nodejs

WORKDIR /app

ENV NODE_ENV=production
ENV NUXT_TELEMETRY_DISABLED=1
ENV PORT=8080
ENV API_PORT=9000
ENV NUXT_PORT=3000

# Content and plans are baked in: App Platform has no volumes, and the api
# refuses to boot without either. `ohara` is a named build context, not part of
# this repo — `make image` passes it with --build-context. billing.yaml is
# gitignored and generated by `make prices-apply`, so it is whichever stripe
# account that last ran against.
ENV CONTENT_PATH=/app/content
ENV BILLING_PLANS=/app/billing.yaml
COPY --from=ohara books /app/content/books
COPY --from=ohara projects /app/content/projects
COPY billing.yaml /app/billing.yaml

COPY Caddyfile /etc/caddy/Caddyfile
COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
COPY --from=api-build /usr/local/bin/lighthouse-api /usr/local/bin/lighthouse-api
COPY --from=web-build /build/.output /app/web

RUN chmod +x /usr/local/bin/entrypoint.sh \
    && addgroup -S lighthouse && adduser -S -G lighthouse lighthouse \
    && chown -R lighthouse:lighthouse /app /etc/caddy

# Caddy binds 8080, not 80, so it does not need CAP_NET_BIND_SERVICE and can
# drop to an unprivileged user.
USER lighthouse

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=20s --retries=3 \
    CMD wget -qO- "http://127.0.0.1:${PORT}/" > /dev/null || exit 1

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
