// Generated by `lighthouse-prices catalogue`. Do not edit.
//
// The amounts are declared in pricing.yaml and the shelf comes from
// ohara; both are read at generation time, not at build time, because
// the web image is built from `web/` alone and can reach neither.
//
// Regenerate with `make catalogue` in the thelighthouse repo, and
// commit the result — `/pricing` is prerendered, so this file is what
// the built page says. A price changed in stripe and not here is a
// page advertising the wrong number.

// One purchasable plan. The same shape `/api/billing/plans` answers
// with, so nothing downstream can tell which one it came from.
export interface CataloguePlan {
  plan: string
  track: string
  recurring: boolean
  amount: number
  currency: string
}

// A book, and the tracks it is on with its position in each.
export interface CatalogueBook {
  slug: string
  title: string
  tracks: Record<string, number>
}

export const plans: CataloguePlan[] = [
  {
    "plan": "foundation_yearly",
    "track": "foundation",
    "recurring": true,
    "amount": 9900,
    "currency": "usd"
  },
  {
    "plan": "all_yearly",
    "track": "all",
    "recurring": true,
    "amount": 24900,
    "currency": "usd"
  }
]

export const shelf: CatalogueBook[] = [
  {
    "slug": "c-programming",
    "title": "C Programming",
    "tracks": {}
  },
  {
    "slug": "crack-the-interview",
    "title": "Crack the Interview — 15 Algorithmic Patterns",
    "tracks": {}
  },
  {
    "slug": "dsa-fundamentals",
    "title": "DSA Fundamentals",
    "tracks": {
      "foundation": 3,
      "go": 6,
      "rust": 5
    }
  },
  {
    "slug": "go-fundamentals",
    "title": "Go Fundamentals",
    "tracks": {
      "go": 1
    }
  },
  {
    "slug": "go-intermediate",
    "title": "Go Intermediate",
    "tracks": {
      "go": 2
    }
  },
  {
    "slug": "networking-fundamentals",
    "title": "Networking Fundamentals",
    "tracks": {
      "foundation": 2,
      "go": 5,
      "rust": 4
    }
  },
  {
    "slug": "os-fundamentals",
    "title": "OS Fundamentals",
    "tracks": {
      "foundation": 1,
      "go": 4,
      "rust": 3
    }
  },
  {
    "slug": "rust-101s",
    "title": "Rust 101s",
    "tracks": {
      "rust": 2
    }
  },
  {
    "slug": "rust-from-zero",
    "title": "Rust from Zero",
    "tracks": {
      "rust": 1
    }
  },
  {
    "slug": "shipping-go-web-services",
    "title": "Shipping Go Web Services",
    "tracks": {
      "go": 3
    }
  }
]
